### ISSUE TITLE
Home view background color

### ISSUE THREAD

**Issue by mizufluffy** [atumpt/Steam-CSS-Skins#1]
One of the wishes I noticed during the Steam Library open beta period was a darker background color for the Home view.  I tested out a few options that should look better than default light gray option.  

```
/* Darker Home view background color, alternative options are commented out */
.libraryhome_Container_2gSXC {
  background: radial-gradient(100% 100% at 45% 45%, #202731 0%, #24282F 100%); 
  /* 
  background: #1B2838; 
  background: #23272D; 
  */ 
}
```
The default color in this code is radial-gradient because the original light gray color was done in the same way. I kept the other settings but changed start and end colors. The other two alternative options are simple hex colors for the sake of being more easily understood examples. 
#1B2838 is somewhat bluish color that is used as a background on Steam discusssions and #23272D is similar to the color used in the radial-gradient. 
Also, this should be easy to modify by anyone who can look up hex colors on the internet if someone wants to use a different color.

**Comment by atumpt** [comment]
Thanks, this looks pretty good. I've added it to my personal skin.

Would you like to make a PR and add a skin for this?

**Comment by mizufluffy** [comment]
Closing this issue due to PR #2
